# This workflow publish to QA by connecting to the environment via SSH and pulling all repos.
# The web server instances will hotload the changes, as a result.

name: Metriq QA Deployment

on:
  push:
    branches: [ main ]

jobs:
  deployment:

    runs-on: ubuntu-latest
    environment: qa

    steps:
      name: Deploy to QA
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        ssh -i key.pem ${{ secrets.QA_LOGIN }}
        cd GitHub/metriq-api
        git pull
        cd metriq-api
        git pull
        cd ..
        cd metriq-app
        git pull
        exit
        rm key.pem
